### ISSUE TITLE
Fix retarded date pls

### ISSUE THREAD

**Issue by furtivesock** [Aleryc/is-it-my-birthday-today#1]
omg how dare you :((

**Comment by Aleryc** [comment]
No u

**Comment by furtivesock** [comment]
This date format is so so confusing 😢 
pls

**Comment by Aleryc** [comment]
Dis app adapts to ur fave env so thus means ur ritarded n confusing lol

**Comment by furtivesock** [comment]
oh okay right
thx for ur expertise captain im closing dis issue 👍

**Comment by Aleryc** [comment]
Ur welcom
